### PANDAS

In [97]:
pip install pandas

Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [98]:
import pandas as pd

In [76]:
pd.__version__

'2.3.3'

In [99]:
# df1 = pd.DataFrame([10,20,30])
# df1
df2 = pd.DataFrame(["Angel" , "sneha","riya"],columns = ["names of students"])
print(df2)
print(type(df2))

  names of students
0             Angel
1             sneha
2              riya
<class 'pandas.core.frame.DataFrame'>

In [100]:
data = {"name" : ["Angel" , "Alka" , "Sneha" , "Riya" , "Maya" ],
        "age" : [18,19,18,21,33],
        "marks" : [90,93,99,99,67]
       }
data

{'name': ['Angel', 'Alka', 'Sneha', 'Riya', 'Maya'],
 'age': [18, 19, 18, 21, 33],
 'marks': [90, 93, 99, 99, 67]}

In [101]:
df = pd.DataFrame(data)
print(df)
print(type(df))
df.head(2)

    name  age  marks
0  Angel   18     90
1   Alka   19     93
2  Sneha   18     99
3   Riya   21     99
4   Maya   33     67
<class 'pandas.core.frame.DataFrame'>

    name  age  marks
0  Angel   18     90
1   Alka   19     93

In [59]:
df.tail(2)

   name  age  marks
3  Riya   21     99
4  Maya   33     67

In [60]:
df.shape

(5, 3)

In [80]:
df.columns

Index(['name', 'age', 'marks'], dtype='object')

In [102]:
df.rename (columns = {"age" : "student age" } ,inplace = True)
df

    name  student age  marks
0  Angel           18     90
1   Alka           19     93
2  Sneha           18     99
3   Riya           21     99
4   Maya           33     67

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          5 non-null      object
 1   student age   5 non-null      int64
 2   marks         5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [83]:
df.describe()

       student age       marks
count      5.000000   5.000000
mean      21.800000  89.600000
std        6.379655  13.221195
min       18.000000  67.000000
25%       18.000000  90.000000
50%       19.000000  93.000000
75%       21.000000  99.000000
max       33.000000  99.000000

In [84]:
df.to_csv("Test_data.csv" , index = False)
load_df = pd.read_csv("Test_data.csv")
load_df

    name  student age   marks
0  Angel            18     90
1   Alka            19     93
2  Sneha            18     99
3   Riya            21     99
4   Maya            33     67

In [85]:
pd.read_csv ("Test_data.csv")

    name  student age   marks
0  Angel            18     90
1   Alka            19     93
2  Sneha            18     99
3   Riya            21     99
4   Maya            33     67

In [86]:
df.loc[df.name == 'Angel']

    name  student age   marks
0  Angel            18     90

In [87]:
df.loc[(df.name=='Angel') & (df.marks == 90)]

    name  student age   marks
0  Angel            18     90

In [88]:
df.iloc[0:2]

    name  student age   marks
0  Angel            18     90
1   Alka            19     93

In [89]:
df.loc[0:2]

    name  student age   marks
0  Angel            18     90
1   Alka            19     93
2  Sneha            18     99

In [94]:
df['student age'] >=19

KeyError: 'student age'

In [72]:
df.where(df["age"]>18)

KeyError: 'age'

In [24]:
df.where(df['age']>18 , other = "pagal")

    name    age  marks
0  pagal  pagal  pagal
1   Alka     19     93
2  pagal  pagal  pagal
3   Riya     21     99
4   Maya     33     67

In [53]:
df['team'] = ['go3d' , 'go3d' , 'techbyte' , 'techbyte' , 'go3d']
print(df)

ValueError: Length of values (5) does not match length of index (4)

In [35]:
df['percent' ] = (df["marks" ] /200 ) *100

In [36]:
df

    name  age  marks      team  grades  percent
0  Angel   18     90      go3d    45.0     45.0
1   Alka   19     93      go3d    46.5     46.5
2  Sneha   18     99  techbyte    49.5     49.5
3   Riya   21     99  techbyte    49.5     49.5
4   Maya   33     67      go3d    33.5     33.5

In [38]:
df.loc[0,"name"] = "Annie"
df

    name  age  marks      team  grades  percent
0  Annie   18     90      go3d    45.0     45.0
1   Alka   19     93      go3d    46.5     46.5
2  Sneha   18     99  techbyte    49.5     49.5
3   Riya   21     99  techbyte    49.5     49.5
4   Maya   33     67      go3d    33.5     33.5

In [39]:
df.loc[df.name == "Sneha" , "marks"] = 80
df

    name  age  marks      team  grades  percent
0  Annie   18     90      go3d    45.0     45.0
1   Alka   19     93      go3d    46.5     46.5
2  Sneha   18     80  techbyte    49.5     49.5
3   Riya   21     99  techbyte    49.5     49.5
4   Maya   33     67      go3d    33.5     33.5

In [ ]:
df.drop()

In [41]:
df = df.drop(df[df.name == "Maya" ].index)
df

    name  age  marks      team  grades  percent
0  Annie   18     90      go3d    45.0     45.0
1   Alka   19     93      go3d    46.5     46.5
2  Sneha   18     80  techbyte    49.5     49.5
3   Riya   21     99  techbyte    49.5     49.5

In [43]:
df.drop(1,axis=0)
df

    name  age  marks      team  grades  percent
0  Annie   18     90      go3d    45.0     45.0
1   Alka   19     93      go3d    46.5     46.5
2  Sneha   18     80  techbyte    49.5     49.5
3   Riya   21     99  techbyte    49.5     49.5

In [50]:
df.drop('team',axis=1,inplace=True)
df

KeyError: "['team'] not found in axis"

In [106]:
df.sort_values('student age',ascending = True , inplace = True)
df

    name  student age  marks
0  Angel           18     90
2  Sneha           18     99
1   Alka           19     93
3   Riya           21     99
4   Maya           33     67

In [104]:
df

    name  student age  marks
0  Angel           18     90
1   Alka           19     93
2  Sneha           18     99
3   Riya           21     99
4   Maya           33     67

In [113]:
df['doj']=['20-12-2007','30-12-2007','01-01-2008','23-04-2008','09-09-2009']
df

    name  student age  marks         doj
0  Angel           18     90  20-12-2007
2  Sneha           18     99  30-12-2007
1   Alka           19     93  01-01-2008
3   Riya           21     99  23-04-2008
4   Maya           33     67  09-09-2009

In [115]:
df["doj"] =pd.to_datetime(df["doj"])

C:\Users\ACER\AppData\Local\Temp\ipykernel_15796\2147076749.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["doj"] =pd.to_datetime(df["doj"])

In [116]:
df["doj"].dtype

dtype('<M8[ns]')

In [117]:
df["doj"].dt.year

0    2007
2    2007
1    2008
3    2008
4    2009
Name: doj, dtype: int32

In [118]:
df["doj"].dt.month

0    12
2    12
1     1
3     4
4     9
Name: doj, dtype: int32

In [121]:
df["doj"].dt.day_name()

0     Thursday
2       Sunday
1      Tuesday
3    Wednesday
4    Wednesday
Name: doj, dtype: object

In [120]:
df["doj"].dt.date

0    2007-12-20
2    2007-12-30
1    2008-01-01
3    2008-04-23
4    2009-09-09
Name: doj, dtype: object

In [123]:
df.isnull()

    name  student age  marks    doj
0  False        False  False  False
2  False        False  False  False
1  False        False  False  False
3  False        False  False  False
4  False        False  False  False

In [125]:
import numpy as np 
df.loc[df.name =="Riya" , "marks"] = np.nan

In [126]:
df

    name  student age  marks        doj
0  Angel           18   90.0 2007-12-20
2  Sneha           18   99.0 2007-12-30
1   Alka           19   93.0 2008-01-01
3   Riya           21    NaN 2008-04-23
4   Maya           33   67.0 2009-09-09

In [127]:
df.isnull()

    name  student age  marks    doj
0  False        False  False  False
2  False        False  False  False
1  False        False  False  False
3  False        False   True  False
4  False        False  False  False

In [128]:
df.isnull().sum()

name           0
student age    0
marks          1
doj            0
dtype: int64

In [129]:
df.fillna(0)

    name  student age  marks        doj
0  Angel           18   90.0 2007-12-20
2  Sneha           18   99.0 2007-12-30
1   Alka           19   93.0 2008-01-01
3   Riya           21    0.0 2008-04-23
4   Maya           33   67.0 2009-09-09

In [131]:
df.loc[df.name=="Riya" , "marks" ] = 78
df

    name  student age  marks        doj
0  Angel           18   90.0 2007-12-20
2  Sneha           18   99.0 2007-12-30
1   Alka           19   93.0 2008-01-01
3   Riya           21   78.0 2008-04-23
4   Maya           33   67.0 2009-09-09

In [144]:
df1 = pd.DataFrame({'id':[1,2,3] , 'name': ['A' , 'B' , 'C' ]})

In [146]:
DF2 = pd.DataFrame({'id' : [1,2,3] , 'name' : ['d' , 'e' , 'f' ]})

In [148]:
pd.concat([df1,DF2] , axis = 1)

   id name  id name
0   1    A   1    d
1   2    B   2    e
2   3    C   3    f

In [152]:
df3 = pd.concat([df1,DF2] , axis = 0)
df3

   id name
0   1    A
1   2    B
2   3    C
0   1    d
1   2    e
2   3    f

In [155]:
pd.merge(df1, DF2, how = 'inner')

Empty DataFrame
Columns: [id, name]
Index: []

In [157]:
df

    name  student age  marks        doj
0  Angel           18   90.0 2007-12-20
2  Sneha           18   99.0 2007-12-30
1   Alka           19   93.0 2008-01-01
3   Riya           21   78.0 2008-04-23
4   Maya           33   67.0 2009-09-09

In [159]:
df.query("student age == 18 and marks >= 95" )

SyntaxError: Python keyword not valid identifier in numexpr query (<unknown>, line 1)